<?php

return [
    'context_groups' => [
        'dashboard' => [
            'label' => 'Dashboard',
            'icon' => 'fas fa-tachometer-alt',
            'order' => 10,
            'route' => NULL,
            'url' => 'organization/dashboard-overview',
        ],
        'companies' => [
            'label' => 'Companies',
            'icon' => 'fas fa-building',
            'order' => 20,
            'route' => NULL,
            'url' => 'organization/dashboard-companies-overview',
        ],
        'structure' => [
            'label' => 'Structure',
            'icon' => 'fas fa-sitemap',
            'order' => 30,
            'route' => NULL,
            'url' => 'organization/dashboard-structure-overview',
        ],
        'teams' => [
            'label' => 'Teams',
            'icon' => 'fas fa-users',
            'order' => 40,
            'route' => NULL,
            'url' => 'organization/teams',
        ],
        'locations' => [
            'label' => 'Locations',
            'icon' => 'fas fa-map-marker-alt',
            'order' => 50,
            'route' => NULL,
            'url' => 'organization/dashboard-locations-overview',
        ],
        'classification' => [
            'label' => 'Classification',
            'icon' => 'fas fa-tags',
            'order' => 60,
            'route' => NULL,
            'url' => 'organization/dashboard-classification-overview',
        ],
        'reports' => [
            'label' => 'Reports',
            'icon' => 'fas fa-file-alt',
            'order' => 70,
            'route' => NULL,
            'url' => 'organization/dashboard-reports-overview',
        ],
    ],

    'contexts' => [
        'dashboard' => [
            [
                'key' => 'dashboard_overview',
                'label' => 'Overview',
                'icon' => 'fas fa-chart-bar',
                'route' => '/organization/dashboard-overview',
                'permission' => 'view_dashboard_overview',
                'order' => 1,
                'page_title' => NULL,
            ],
            [
                'key' => 'organization_summary',
                'label' => 'Organization Summary',
                'icon' => 'fas fa-chart-pie',
                'route' => '/organization/dashboard/organization-summary',
                'permission' => 'view_organization_summary',
                'order' => 10,
                'page_title' => NULL,
            ],
            [
                'key' => 'growth',
                'label' => 'Growth',
                'icon' => 'fas fa-chart-line',
                'route' => '/organization/dashboard/growth',
                'permission' => 'view_growth',
                'order' => 20,
                'page_title' => NULL,
            ],
            [
                'key' => 'recent_changes',
                'label' => 'Recent Changes',
                'icon' => 'fas fa-stream',
                'route' => '/organization/dashboard/recent-changes',
                'permission' => 'view_recent_changes',
                'order' => 30,
                'page_title' => NULL,
            ],
        ],
        'companies' => [
            [
                'key' => 'companies_overview',
                'label' => 'Overview',
                'icon' => 'fas fa-chart-bar',
                'route' => '/organization/dashboard-companies-overview',
                'permission' => 'view_companies_overview',
                'order' => 1,
                'page_title' => NULL,
            ],
            [
                'key' => 'company',
                'label' => 'All Companies',
                'route' => '/organization/companies',
                'icon' => 'fas fa-building',
                'permission' => 'view_company',
                'order' => 10,
                'page_title' => NULL,
            ],
            [
                'key' => 'branch',
                'label' => 'Branches',
                'route' => '/organization/branches',
                'icon' => 'fas fa-code-branch',
                'permission' => 'view_branch',
                'order' => 20,
                'page_title' => NULL,
            ],
            [
                'key' => 'business_unit',
                'label' => 'Business Units',
                'route' => '/organization/business-units',
                'icon' => 'fas fa-briefcase',
                'permission' => 'view_business_unit',
                'order' => 30,
                'page_title' => NULL,
            ],
            [
                'key' => 'legal_entity',
                'label' => 'Legal Entities',
                'route' => '/organization/legal-entities',
                'icon' => 'fas fa-gavel',
                'permission' => 'view_legal_entity',
                'order' => 40,
                'page_title' => NULL,
            ],
        ],
        'structure' => [
            [
                'key' => 'structure_overview',
                'label' => 'Overview',
                'icon' => 'fas fa-chart-bar',
                'route' => '/organization/dashboard-structure-overview',
                'permission' => 'view_structure_overview',
                'order' => 1,
                'page_title' => NULL,
            ],
            [
                'key' => 'department',
                'label' => 'Departments',
                'route' => '/organization/departments',
                'icon' => 'fas fa-layer-group',
                'permission' => 'view_department',
                'order' => 10,
                'page_title' => NULL,
            ],
            [
                'key' => 'division',
                'label' => 'Divisions',
                'route' => '/organization/divisions',
                'icon' => 'fas fa-diagram-project',
                'permission' => 'view_division',
                'order' => 20,
                'page_title' => NULL,
            ],
            [
                'key' => 'organization_chart',
                'label' => 'Organization Chart',
                'route' => '/organization/organization-chart',
                'icon' => 'fas fa-project-diagram',
                'permission' => 'view_organization_chart',
                'order' => 30,
                'page_title' => NULL,
            ],
        ],
        'teams' => [
            [
                'key' => 'team',
                'label' => 'All Teams',
                'route' => '/organization/teams',
                'icon' => 'fas fa-people-group',
                'permission' => 'view_team',
                'order' => 10,
                'page_title' => NULL,
            ],
        ],
        'locations' => [
            [
                'key' => 'locations_overview',
                'label' => 'Overview',
                'icon' => 'fas fa-chart-bar',
                'route' => '/organization/dashboard-locations-overview',
                'permission' => 'view_locations_overview',
                'order' => 1,
                'page_title' => NULL,
            ],
            [
                'key' => 'location',
                'label' => 'All Locations',
                'route' => '/organization/locations',
                'icon' => 'fas fa-location-dot',
                'permission' => 'view_location',
                'order' => 10,
                'page_title' => NULL,
            ],
            [
                'key' => 'region',
                'label' => 'Regions',
                'route' => '/organization/regions',
                'icon' => 'fas fa-map',
                'permission' => 'view_region',
                'order' => 20,
                'page_title' => NULL,
            ],
            [
                'key' => 'country',
                'label' => 'Countries',
                'route' => '/organization/countries',
                'icon' => 'fas fa-globe',
                'permission' => 'view_country',
                'order' => 30,
                'page_title' => NULL,
            ],
            [
                'key' => 'address',
                'label' => 'Addresses',
                'route' => '/organization/addresses',
                'icon' => 'fas fa-map-pin',
                'permission' => 'view_address',
                'order' => 40,
                'page_title' => NULL,
            ],
        ],
        'classification' => [
            [
                'key' => 'classification_overview',
                'label' => 'Overview',
                'icon' => 'fas fa-chart-bar',
                'route' => '/organization/dashboard-classification-overview',
                'permission' => 'view_classification_overview',
                'order' => 1,
                'page_title' => NULL,
            ],
            [
                'key' => 'tag',
                'label' => 'Tags',
                'route' => '/organization/tags',
                'icon' => 'fas fa-tag',
                'permission' => 'view_tag',
                'order' => 10,
                'page_title' => NULL,
            ],
            [
                'key' => 'category',
                'label' => 'Categories',
                'route' => '/organization/categories',
                'icon' => 'fas fa-folder-open',
                'permission' => 'view_category',
                'order' => 20,
                'page_title' => NULL,
            ],
            [
                'key' => 'label',
                'label' => 'Labels',
                'route' => '/organization/labels',
                'icon' => 'fas fa-bookmark',
                'permission' => 'view_label',
                'order' => 30,
                'page_title' => NULL,
            ],
            [
                'key' => 'custom_field',
                'label' => 'Custom Fields',
                'route' => '/organization/custom-fields',
                'icon' => 'fas fa-list-alt',
                'permission' => 'view_custom_field',
                'order' => 40,
                'page_title' => NULL,
            ],
        ],
        'reports' => [
            [
                'key' => 'reports_overview',
                'label' => 'Overview',
                'icon' => 'fas fa-chart-bar',
                'route' => '/organization/dashboard-reports-overview',
                'permission' => 'view_reports_overview',
                'order' => 1,
                'page_title' => NULL,
            ],
            [
                'key' => 'company_reports',
                'label' => 'Company Reports',
                'route' => '/organization/reports/companies',
                'icon' => 'fas fa-file-alt',
                'permission' => 'view_company_reports',
                'order' => 10,
                'page_title' => NULL,
            ],
            [
                'key' => 'department_reports',
                'label' => 'Department Reports',
                'route' => '/organization/reports/departments',
                'icon' => 'fas fa-file-alt',
                'permission' => 'view_department_reports',
                'order' => 20,
                'page_title' => NULL,
            ],
            [
                'key' => 'location_reports',
                'label' => 'Location Reports',
                'route' => '/organization/reports/locations',
                'icon' => 'fas fa-file-alt',
                'permission' => 'view_location_reports',
                'order' => 30,
                'page_title' => NULL,
            ],
            [
                'key' => 'growth_reports',
                'label' => 'Growth Reports',
                'route' => '/organization/reports/growth',
                'icon' => 'fas fa-chart-line',
                'permission' => 'view_growth_reports',
                'order' => 40,
                'page_title' => NULL,
            ],
        ],
    ],

    'sidebar' => [
        'section_label' => null,
        'collapsible' => true,
        'expanded_default' => true,
    ],

    'layout' => [
        'top_bar' => [
            'enabled' => true,
        ],
        'context_menu' => [
            'type' => 'sidebar',
            'position' => 'left',
            'allow_switch' => true,
            'default_type' => 'sidebar',

            // Phase 1 — overflow
            'max_visible_items' => 6,
            'promote_active_item' => true,

            // Phase 2 — Cross-Context Dropdowns
            'show_all_contexts' => false,
            'hide_topnav_contexts' => false,
        ],
        'sidebar' => [
            'initial_state' => 'full',
        ],
        'bottom_bar' => [
            'enabled' => true,
        ],
        'breadcrumb' => [
            'enabled' => true,
        ],
        'title' => [
            'enabled' => true,
        ],
    ],
    'shared_items' => [
        'header' => [],
        'footer' => [],
    ],
    'shared_top_items' => [
        'left' => [],
        'right' => [],
    ],
];
