<?php

return [
    'context_groups' => [
        'dashboard' => [
            'label' => 'Dashboard',
            'icon' => 'fas fa-tachometer-alt',
            'order' => 10,
            'route' => NULL,
            'url' => 'system/dashboard-overview',
        ],
        'accounts' => [
            'label' => 'Accounts',
            'icon' => 'fas fa-id-card',
            'order' => 20,
            'route' => NULL,
            'url' => 'system/dashboard-accounts-overview',
        ],
        'subscriptions' => [
            'label' => 'Subscriptions',
            'icon' => 'fas fa-sync-alt',
            'order' => 30,
            'route' => NULL,
            'url' => 'system/dashboard-subscriptions-overview',
        ],
        'plans' => [
            'label' => 'Plans',
            'icon' => 'fas fa-layer-group',
            'order' => 40,
            'route' => NULL,
            'url' => 'system/dashboard-plans-overview',
        ],
        'applications' => [
            'label' => 'Applications',
            'icon' => 'fas fa-th-large',
            'order' => 50,
            'route' => NULL,
            'url' => 'system/dashboard-applications-overview',
        ],
        'settings' => [
            'label' => 'System Settings',
            'icon' => 'fas fa-cog',
            'order' => 60,
            'route' => NULL,
            'url' => 'system/dashboard-settings-overview',
        ],
        'setup' => [
            'label' => 'Setup',
            'icon' => 'fas fa-magic',
            'order' => 70,
            'route' => NULL,
            'url' => 'system/dashboard-setup-overview',
        ],
    ],

    'contexts' => [
        'dashboard' => [
            [
                'key' => 'dashboard_overview',
                'label' => 'Overview',
                'icon' => 'fas fa-chart-bar',
                'route' => '/system/dashboard-overview',
                'permission' => 'view_dashboard_overview',
                'order' => 1,
                'page_title' => NULL,
            ],
            [
                'key' => 'platform_health',
                'label' => 'Platform Health',
                'icon' => 'fas fa-heartbeat',
                'route' => '/system/platform-health',
                'permission' => 'view_platform_health',
                'order' => 10,
                'page_title' => NULL,
            ],
            [
                'key' => 'recent_activity',
                'label' => 'Recent Activity',
                'icon' => 'fas fa-stream',
                'route' => '/system/recent-activity',
                'permission' => 'view_recent_activity',
                'order' => 20,
                'page_title' => NULL,
            ],
            [
                'key' => 'usage_statistics',
                'label' => 'Usage Statistics',
                'icon' => 'fas fa-chart-line',
                'route' => '/system/usage-statistics',
                'permission' => 'view_usage_statistics',
                'order' => 30,
                'page_title' => NULL,
            ],
            [
                'key' => 'notifications',
                'label' => 'Notifications',
                'icon' => 'fas fa-bell',
                'route' => '/system/notifications',
                'permission' => 'view_notification',
                'order' => 40,
                'page_title' => NULL,
            ],
        ],
        'accounts' => [
            [
                'key' => 'accounts_overview',
                'label' => 'Overview',
                'icon' => 'fas fa-chart-bar',
                'route' => '/system/dashboard-accounts-overview',
                'permission' => 'view_accounts_overview',
                'order' => 1,
                'page_title' => NULL,
            ],
            [
                'key' => 'account',
                'label' => 'Accounts',
                'icon' => 'fas fa-id-card',
                'route' => '/system/accounts',
                'permission' => 'view_account',
                'order' => 10,
                'page_title' => NULL,
            ],
            [
                'key' => 'account_group',
                'label' => 'Account Groups',
                'icon' => 'fas fa-layer-group',
                'route' => '/system/account-groups',
                'permission' => 'view_account_group',
                'order' => 20,
                'page_title' => NULL,
            ],
            [
                'key' => 'account_status',
                'label' => 'Account Statuses',
                'icon' => 'fas fa-toggle-on',
                'route' => '/system/account-statuses',
                'permission' => 'view_account_status',
                'order' => 30,
                'page_title' => NULL,
            ],
            [
                'key' => 'invitation',
                'label' => 'Invitations',
                'icon' => 'fas fa-envelope-open-text',
                'route' => '/system/invitations',
                'permission' => 'view_invitation',
                'order' => 40,
                'page_title' => NULL,
            ],
            [
                'key' => 'account_activity',
                'label' => 'Account Activity',
                'icon' => 'fas fa-history',
                'route' => '/system/account-activity',
                'permission' => 'view_account_activity',
                'order' => 50,
                'page_title' => NULL,
            ],
        ],
        'subscriptions' => [
            [
                'key' => 'subscriptions_overview',
                'label' => 'Overview',
                'icon' => 'fas fa-chart-bar',
                'route' => '/system/dashboard-subscriptions-overview',
                'permission' => 'view_subscriptions_overview',
                'order' => 1,
                'page_title' => NULL,
            ],
            [
                'key' => 'subscription',
                'label' => 'Subscriptions',
                'icon' => 'fas fa-sync-alt',
                'route' => '/system/subscriptions',
                'permission' => 'view_subscription',
                'order' => 10,
                'page_title' => NULL,
            ],
            [
                'key' => 'trial',
                'label' => 'Trials',
                'icon' => 'fas fa-flask',
                'route' => '/system/trials',
                'permission' => 'view_trial',
                'order' => 20,
                'page_title' => NULL,
            ],
            [
                'key' => 'renewal',
                'label' => 'Renewals',
                'icon' => 'fas fa-redo-alt',
                'route' => '/system/renewals',
                'permission' => 'view_renewal',
                'order' => 30,
                'page_title' => NULL,
            ],
            [
                'key' => 'invoice',
                'label' => 'Invoices',
                'icon' => 'fas fa-file-invoice',
                'route' => '/system/invoices',
                'permission' => 'view_invoice',
                'order' => 40,
                'page_title' => NULL,
            ],
            [
                'key' => 'payment',
                'label' => 'Payments',
                'icon' => 'fas fa-credit-card',
                'route' => '/system/payments',
                'permission' => 'view_payment',
                'order' => 50,
                'page_title' => NULL,
            ],
            [
                'key' => 'subscription_history',
                'label' => 'Subscription History',
                'icon' => 'fas fa-history',
                'route' => '/system/subscription-history',
                'permission' => 'view_subscription_history',
                'order' => 60,
                'page_title' => NULL,
            ],
        ],
        'plans' => [
            [
                'key' => 'plans_overview',
                'label' => 'Overview',
                'icon' => 'fas fa-chart-bar',
                'route' => '/system/dashboard-plans-overview',
                'permission' => 'view_plans_overview',
                'order' => 1,
                'page_title' => NULL,
            ],
            [
                'key' => 'plan',
                'label' => 'Plans',
                'icon' => 'fas fa-layer-group',
                'route' => '/system/plans',
                'permission' => 'view_plan',
                'order' => 10,
                'page_title' => NULL,
            ],
            [
                'key' => 'feature',
                'label' => 'Features',
                'icon' => 'fas fa-star',
                'route' => '/system/features',
                'permission' => 'view_feature',
                'order' => 20,
                'page_title' => NULL,
            ],
            [
                'key' => 'limit',
                'label' => 'Limits',
                'icon' => 'fas fa-tachometer-alt',
                'route' => '/system/limits',
                'permission' => 'view_limit',
                'order' => 30,
                'page_title' => NULL,
            ],
            [
                'key' => 'pricing',
                'label' => 'Pricing',
                'icon' => 'fas fa-tags',
                'route' => '/system/pricing',
                'permission' => 'view_pricing',
                'order' => 40,
                'page_title' => NULL,
            ],
            [
                'key' => 'promotion',
                'label' => 'Promotions',
                'icon' => 'fas fa-percent',
                'route' => '/system/promotions',
                'permission' => 'view_promotion',
                'order' => 50,
                'page_title' => NULL,
            ],
        ],
        'applications' => [
            [
                'key' => 'applications_overview',
                'label' => 'Overview',
                'icon' => 'fas fa-chart-bar',
                'route' => '/system/dashboard-applications-overview',
                'permission' => 'view_applications_overview',
                'order' => 1,
                'page_title' => NULL,
            ],
            [
                'key' => 'installed_application',
                'label' => 'Installed Applications',
                'icon' => 'fas fa-th-large',
                'route' => '/system/installed-applications',
                'permission' => 'view_installed_application',
                'order' => 10,
                'page_title' => NULL,
            ],
            [
                'key' => 'marketplace',
                'label' => 'Marketplace',
                'icon' => 'fas fa-store',
                'route' => '/system/marketplace',
                'permission' => 'view_marketplace',
                'order' => 20,
                'page_title' => NULL,
            ],
            [
                'key' => 'dependency',
                'label' => 'Dependencies',
                'icon' => 'fas fa-puzzle-piece',
                'route' => '/system/dependencies',
                'permission' => 'view_dependency',
                'order' => 30,
                'page_title' => NULL,
            ],
            [
                'key' => 'version',
                'label' => 'Versions',
                'icon' => 'fas fa-code-branch',
                'route' => '/system/versions',
                'permission' => 'view_version',
                'order' => 40,
                'page_title' => NULL,
            ],
            [
                'key' => 'update',
                'label' => 'Updates',
                'icon' => 'fas fa-sync-alt',
                'route' => '/system/updates',
                'permission' => 'view_update',
                'order' => 50,
                'page_title' => NULL,
            ],
        ],
        'settings' => [
            [
                'key' => 'settings_overview',
                'label' => 'Overview',
                'icon' => 'fas fa-chart-bar',
                'route' => '/system/dashboard-settings-overview',
                'permission' => 'view_settings_overview',
                'order' => 1,
                'page_title' => NULL,
            ],
            [
                'key' => 'system_setting',
                'label' => 'General Settings',
                'route' => '/system/settings',
                'icon' => 'fas fa-sliders-h',
                'permission' => 'view_system_setting',
                'order' => 10,
                'page_title' => NULL,
            ],
            [
                'key' => 'branding',
                'label' => 'Branding',
                'icon' => 'fas fa-palette',
                'route' => '/system/settings/branding',
                'permission' => 'view_branding',
                'order' => 20,
                'page_title' => NULL,
            ],
            [
                'key' => 'localization',
                'label' => 'Localization',
                'icon' => 'fas fa-globe',
                'route' => '/system/settings/localization',
                'permission' => 'view_localization',
                'order' => 30,
                'page_title' => NULL,
            ],
            [
                'key' => 'email_settings',
                'label' => 'Email',
                'icon' => 'fas fa-envelope',
                'route' => '/system/settings/email',
                'permission' => 'view_email_settings',
                'order' => 40,
                'page_title' => NULL,
            ],
            [
                'key' => 'notification_settings',
                'label' => 'Notifications',
                'icon' => 'fas fa-bell',
                'route' => '/system/settings/notifications',
                'permission' => 'view_notification_settings',
                'order' => 50,
                'page_title' => NULL,
            ],
            [
                'key' => 'storage',
                'label' => 'Storage',
                'icon' => 'fas fa-database',
                'route' => '/system/settings/storage',
                'permission' => 'view_storage',
                'order' => 60,
                'page_title' => NULL,
            ],
            [
                'key' => 'security',
                'label' => 'Security',
                'icon' => 'fas fa-shield-alt',
                'route' => '/system/settings/security',
                'permission' => 'view_security',
                'order' => 70,
                'page_title' => NULL,
            ],
            [
                'key' => 'backups',
                'label' => 'Backups',
                'icon' => 'fas fa-cloud-upload-alt',
                'route' => '/system/settings/backups',
                'permission' => 'view_backups',
                'order' => 80,
                'page_title' => NULL,
            ],
            [
                'key' => 'system_logs',
                'label' => 'System Logs',
                'icon' => 'fas fa-clipboard-list',
                'route' => '/system/settings/system-logs',
                'permission' => 'view_system_logs',
                'order' => 90,
                'page_title' => NULL,
            ],
        ],
        'setup' => [
            [
                'key' => 'setup_overview',
                'label' => 'Overview',
                'icon' => 'fas fa-chart-bar',
                'route' => '/system/dashboard-setup-overview',
                'permission' => 'view_setup_overview',
                'order' => 1,
                'page_title' => NULL,
            ],
            [
                'key' => 'setup_wizard',
                'label' => 'Setup Wizard',
                'route' => '/setup/wizard',
                'icon' => 'fas fa-magic',
                'permission' => 'view_setup_wizard',
                'order' => 20,
                'page_title' => NULL,
            ],
        ],
    ],

    'sidebar' => [
        'section_label' => null,
        'collapsible' => true,
        'expanded_default' => true,
    ],

    'layout' => [
        'top_bar' => [
            'enabled' => true,
        ],
        'context_menu' => [
            'type' => 'sidebar',
            'position' => 'left',
            'allow_switch' => true,
            'default_type' => 'sidebar',

            // Phase 1 — overflow
            'max_visible_items' => 6,
            'promote_active_item' => true,

            // Phase 2 — Cross-Context Dropdowns
            'show_all_contexts' => false,
            'hide_topnav_contexts' => false,
        ],
        'sidebar' => [
            'initial_state' => 'full',
        ],
        'bottom_bar' => [
            'enabled' => true,
        ],
        'breadcrumb' => [
            'enabled' => true,
        ],
        'title' => [
            'enabled' => true,
        ],
    ],

    'shared_items' => [
        'header' => [],
        'footer' => [],
    ],

    'shared_top_items' => [
        'left' => [],
        'right' => [],
    ],
];
