<?php

return [
    'context_groups' => [
        'dashboard' => [
            'label' => 'Dashboard',
            'icon' => 'fas fa-tachometer-alt',
            'order' => 1,
            'route' => NULL,
            'url' => 'admin/dashboard',
        ],
        'Users' => [
            'label' => 'Users',
            'icon' => 'fas fa-users',
            'order' => 2,
            'route' => NULL,
            'url' => 'admin/dashboard-users-overview',
        ],
        'Access' => [
            'label' => 'Access',
            'icon' => 'fas fa-shield-alt',
            'order' => 3,
            'route' => NULL,
            'url' => 'admin/dashboard-access-overview',
        ],
        'Workflows' => [
            'label' => 'Workflows',
            'icon' => 'fas fa-project-diagram',
            'order' => 4,
            'route' => NULL,
            'url' => 'admin/dashboard-workflows-overview',
        ],
        'Security' => [
            'label' => 'Security',
            'icon' => 'fas fa-shield-alt',
            'order' => 5,
            'route' => NULL,
            'url' => 'admin/dashboard-security-overview',
        ],
        'audit' => [
            'label' => 'Audit',
            'icon' => 'fas fa-history',
            'order' => 10000,
            'route' => NULL,
            'url' => 'admin/dashboard-audit-overview',
        ],
        'General Settings' => [
            'label' => 'General Settings',
            'icon' => 'fas fa-cogs',
            'order' => 10000,
            'route' => NULL,
            'url' => 'admin/dashboard-settings-overview',
        ],
        'Notifications' => [
            'label' => 'Notifications',
            'icon' => 'fas fa-bell',
            'order' => 10001,
            'route' => NULL,
            'url' => 'admin/dashboard-notifications-overview',
        ],
    ],
    'contexts' => [
        'dashboard' => [
            [
                'key' => 'dashboard_overview',
                'label' => 'Overview',
                'icon' => 'fas fa-chart-bar',
                'route' => '/admin/dashboard-overview',
                'permission' => 'view_dashboard_overview',
                'order' => 1,
                'page_title' => NULL,
            ],
            [
                'key' => 'user_statistics',
                'label' => 'User Statistics',
                'icon' => 'fas fa-chart-pie',
                'route' => '/admin/dashboard/user-statistics',
                'permission' => 'view_user_statistics',
                'order' => 10,
                'page_title' => NULL,
            ],
            [
                'key' => 'role_summary',
                'label' => 'Role Summary',
                'icon' => 'fas fa-user-shield',
                'route' => '/admin/dashboard/role-summary',
                'permission' => 'view_role_summary',
                'order' => 20,
                'page_title' => NULL,
            ],
            [
                'key' => 'recent_activity',
                'label' => 'Recent Activity',
                'icon' => 'fas fa-stream',
                'route' => '/admin/dashboard/recent-activity',
                'permission' => 'view_recent_activity',
                'order' => 30,
                'page_title' => NULL,
            ],
            [
                'key' => 'security_alerts',
                'label' => 'Security Alerts',
                'icon' => 'fas fa-exclamation-triangle',
                'route' => '/admin/dashboard/security-alerts',
                'permission' => 'view_security_alerts',
                'order' => 40,
                'page_title' => NULL,
            ],
        ],
        'Users' => [
            [
                'key' => 'users_overview',
                'label' => 'Overview',
                'icon' => 'fas fa-chart-bar',
                'route' => '/admin/dashboard-users-overview',
                'permission' => 'view_users_overview',
                'order' => 1,
                'page_title' => NULL,
            ],
            [
                'key' => 'user',
                'label' => 'Users',
                'icon' => 'fas fa-user',
                'route' => '/admin/users',
                'permission' => 'view_user',
                'order' => 2,
                'page_title' => NULL,
            ],
            [
                'key' => 'invitation',
                'label' => 'Invitations',
                'icon' => 'fas fa-envelope-open-text',
                'route' => '/admin/invitations',
                'permission' => 'view_invitation',
                'order' => 3,
                'page_title' => NULL,
            ],
            [
                'key' => 'user_group',
                'label' => 'User Groups',
                'icon' => 'fas fa-users',
                'route' => '/admin/user-groups',
                'permission' => 'view_user_group',
                'order' => 4,
                'page_title' => NULL,
            ],
            [
                'key' => 'user_preferences',
                'label' => 'User Preferences',
                'icon' => 'fas fa-sliders-h',
                'route' => '/admin/user-preferences',
                'permission' => 'view_user_preferences',
                'order' => 5,
                'page_title' => NULL,
            ],
        ],
        'Access' => [
            [
                'key' => 'access_overview',
                'label' => 'Overview',
                'icon' => 'fas fa-chart-bar',
                'route' => '/admin/dashboard-access-overview',
                'permission' => 'view_access_overview',
                'order' => 1,
                'page_title' => NULL,
            ],
            [
                'key' => 'role',
                'label' => 'Roles',
                'icon' => 'fas fa-user-shield',
                'route' => '/admin/roles',
                'permission' => 'view_role',
                'order' => 2,
                'page_title' => NULL,
            ],
            [
                'key' => 'access_control',
                'label' => 'Access Control',
                'icon' => 'fas fa-shield-alt',
                'route' => '/admin/access-control-management',
                'permission' => 'view_permission',
                'order' => 3,
                'page_title' => NULL,
            ],
        ],
        'Workflows' => [
            [
                'key' => 'workflows_overview',
                'label' => 'Overview',
                'icon' => 'fas fa-chart-bar',
                'route' => '/admin/dashboard-workflows-overview',
                'permission' => 'view_workflows_overview',
                'order' => 1,
                'page_title' => NULL,
            ],
            [
                'key' => 'workflow_definition',
                'label' => 'Workflow Definitions',
                'icon' => 'fas fa-project-diagram',
                'route' => '/admin/workflow-definitions',
                'permission' => 'view_workflow_definition',
                'order' => 2,
                'page_title' => NULL,
            ],
            [
                'key' => 'workflow_definition_create',
                'label' => 'New Workflow',
                'icon' => 'fas fa-plus',
                'route' => '/admin/workflow-definition-wizard',
                'permission' => 'view_workflow_definition',
                'order' => 3,
                'page_title' => NULL,
            ],
        ],
        'Security' => [
            [
                'key' => 'security_overview',
                'label' => 'Overview',
                'icon' => 'fas fa-chart-bar',
                'route' => '/admin/dashboard-security-overview',
                'permission' => 'view_security_overview',
                'order' => 1,
                'page_title' => NULL,
            ],
            [
                'key' => 'authentication',
                'label' => 'Authentication',
                'icon' => 'fas fa-sign-in-alt',
                'route' => '/admin/security/authentication',
                'permission' => 'view_authentication',
                'order' => 10,
                'page_title' => NULL,
            ],
            [
                'key' => 'password_policies',
                'label' => 'Password Policies',
                'icon' => 'fas fa-key',
                'route' => '/admin/security/password-policies',
                'permission' => 'view_password_policies',
                'order' => 20,
                'page_title' => NULL,
            ],
            [
                'key' => 'multi_factor_authentication',
                'label' => 'Multi-Factor Authentication',
                'icon' => 'fas fa-mobile-alt',
                'route' => '/admin/security/multi-factor-authentication',
                'permission' => 'view_multi_factor_authentication',
                'order' => 30,
                'page_title' => NULL,
            ],
            [
                'key' => 'api_tokens',
                'label' => 'API Tokens',
                'icon' => 'fas fa-code',
                'route' => '/admin/security/api-tokens',
                'permission' => 'view_api_tokens',
                'order' => 40,
                'page_title' => NULL,
            ],
            [
                'key' => 'login_restrictions',
                'label' => 'Login Restrictions',
                'icon' => 'fas fa-ban',
                'route' => '/admin/security/login-restrictions',
                'permission' => 'view_login_restrictions',
                'order' => 50,
                'page_title' => NULL,
            ],
            [
                'key' => 'session',
                'label' => 'Sessions',
                'icon' => 'fas fa-desktop',
                'route' => '/admin/sessions',
                'permission' => 'view_session',
                'order' => 60,
                'page_title' => NULL,
            ],
        ],
        'audit' => [
            [
                'key' => 'audit_overview',
                'label' => 'Overview',
                'icon' => 'fas fa-chart-bar',
                'route' => '/admin/dashboard-audit-overview',
                'permission' => 'view_audit_overview',
                'order' => 1,
                'page_title' => NULL,
            ],
            [
                'key' => 'activity_log',
                'label' => 'Activity Log',
                'icon' => 'fas fa-history',
                'route' => '/admin/activity-logs',
                'permission' => 'view_activity_log',
                'order' => 10,
                'page_title' => 'Activity Log',
            ],
            [
                'key' => 'login_history',
                'label' => 'Login History',
                'icon' => 'fas fa-sign-in-alt',
                'route' => '/admin/login-history',
                'permission' => 'view_login_history',
                'order' => 20,
                'page_title' => 'Login History',
            ],
            [
                'key' => 'system_events',
                'label' => 'System Events',
                'icon' => 'fas fa-server',
                'route' => '/admin/system-events',
                'permission' => 'view_system_events',
                'order' => 30,
                'page_title' => 'System Events',
            ],
            [
                'key' => 'exports',
                'label' => 'Exports',
                'icon' => 'fas fa-download',
                'route' => '/admin/audit-exports',
                'permission' => 'view_audit_exports',
                'order' => 40,
                'page_title' => 'Audit Exports',
            ],
        ],
        'General Settings' => [
            [
                'key' => 'settings_overview',
                'label' => 'Overview',
                'icon' => 'fas fa-chart-bar',
                'route' => '/admin/dashboard-settings-overview',
                'permission' => 'view_settings_overview',
                'order' => 1,
                'page_title' => NULL,
            ],
            [
                'key' => 'system_setting',
                'label' => 'System Settings',
                'icon' => 'fas fa-cog',
                'route' => '/system-settings',
                'permission' => 'view_system_setting',
                'order' => 999,
                'page_title' => NULL,
            ],
        ],
        'Notifications' => [
            [
                'key' => 'notifications_overview',
                'label' => 'Overview',
                'icon' => 'fas fa-chart-bar',
                'route' => '/admin/dashboard-notifications-overview',
                'permission' => 'view_notifications_overview',
                'order' => 1,
                'page_title' => NULL,
                'modelName' => 'notifications_overview',
            ],
            [
                'key' => 'notifications',
                'label' => 'Notifications',
                'icon' => 'fas fa-bell',
                'route' => '/admin/notifications',
                'permission' => 'view_notification',
                'order' => 2,
                'page_title' => NULL,
                'modelName' => 'notifications_index',
            ],
            [
                'key' => 'notification_preferences',
                'label' => 'Preferences',
                'icon' => 'fas fa-sliders-h',
                'route' => '/admin/notification-preferences',
                'permission' => 'view_notification',
                'order' => 3,
                'page_title' => NULL,
                'modelName' => 'notification_preferences',
            ],
            [
                'key' => 'notification_log',
                'label' => 'Notification Logs',
                'icon' => 'fas fa-history',
                'route' => '/admin/notification-logs',
                'permission' => 'view_notification_log',
                'order' => 4,
                'page_title' => 'Notification Logs',
                'modelName' => 'notification_log',
            ],
        ],
    ],
    'sidebar' => [
        'section_label' => null,
        'collapsible' => true,
        'expanded_default' => true,
    ],

    'layout' => [
        'top_bar' => [
            'enabled' => true,
        ],
        'context_menu' => [
            'type' => 'sidebar',
            'position' => 'left',
            'allow_switch' => true,
            'default_type' => 'sidebar',

            // Phase 1 — overflow
            'max_visible_items' => 6,
            'promote_active_item' => true,

            // Phase 2 — Cross-Context Dropdowns
            'show_all_contexts' => false,
            'hide_topnav_contexts' => false,
        ],
        'sidebar' => [
            'initial_state' => 'full',
        ],
        'bottom_bar' => [
            'enabled' => true,
        ],
        'breadcrumb' => [
            'enabled' => true,
        ],
        'title' => [
            'enabled' => true,
        ],
    ],
    'shared_items' => [
        'header' => [],
        'footer' => [],
    ],
    'shared_top_items' => [
        'left' => [],
        'right' => [],
    ],
];
