<?php

/**
 * Admin Module — Quick Actions Configuration
 *
 * Registers common administrative actions for the command palette.
 * These actions appear when the user presses Cmd+K / Ctrl+K.
 */
return [
    'quick_actions' => [
        [
            'id'          => 'admin.view_dashboard',
            'label'       => 'View Dashboard',
            'description' => 'Go to the admin dashboard overview',
            'icon'        => 'fas fa-tachometer-alt',
            'action'      => 'navigate',
            'module'      => 'admin',
            'keywords'    => ['dashboard', 'home', 'overview', 'admin'],
            'category'    => 'Dashboard',
            'route'       => 'admin.dashboard',
            'roles'       => ['super_admin', 'company_admin'],
        ],
        [
            'id'          => 'admin.manage_users',
            'label'       => 'Manage Users',
            'description' => 'View and manage all system users',
            'icon'        => 'fas fa-users',
            'action'      => 'navigate',
            'module'      => 'admin',
            'keywords'    => ['users', 'people', 'accounts', 'staff', 'members'],
            'category'    => 'Users',
            'route'       => 'admin.users',
            'permission'  => 'view_users',
            'roles'       => ['super_admin', 'company_admin'],
        ],
        [
            'id'          => 'admin.manage_roles',
            'label'       => 'Manage Roles',
            'description' => 'View and manage roles and permissions',
            'icon'        => 'fas fa-user-tag',
            'action'      => 'navigate',
            'module'      => 'admin',
            'keywords'    => ['roles', 'permissions', 'access', 'authorization', 'rbac'],
            'category'    => 'Access Control',
            'route'       => 'admin.roles',
            'permission'  => 'view_roles',
            'roles'       => ['super_admin'],
        ],
        [
            'id'          => 'admin.system_settings',
            'label'       => 'System Settings',
            'description' => 'Configure global system settings and preferences',
            'icon'        => 'fas fa-cogs',
            'action'      => 'navigate',
            'module'      => 'admin',
            'keywords'    => ['settings', 'configuration', 'system', 'preferences', 'setup'],
            'category'    => 'Settings',
            'route'       => 'admin.system-settings',
            'permission'  => 'view_system_settings',
            'roles'       => ['super_admin'],
        ],
        [
            'id'          => 'admin.audit_logs',
            'label'       => 'Audit Logs',
            'description' => 'View system audit trails and activity logs',
            'icon'        => 'fas fa-history',
            'action'      => 'navigate',
            'module'      => 'admin',
            'keywords'    => ['audit', 'logs', 'history', 'activity', 'trail', 'tracking'],
            'category'    => 'Audit',
            'route'       => 'admin.activity-logs',
            'permission'  => 'view_audit_logs',
            'roles'       => ['super_admin'],
        ],
        [
            'id'          => 'admin.notifications',
            'label'       => 'Notification Settings',
            'description' => 'Manage notification preferences and templates',
            'icon'        => 'fas fa-bell',
            'action'      => 'navigate',
            'module'      => 'admin',
            'keywords'    => ['notifications', 'alerts', 'email', 'templates', 'preferences'],
            'category'    => 'Settings',
            'route'       => 'admin.notification-preferences',
            'permission'  => 'view_notifications',
            'roles'       => ['super_admin', 'company_admin'],
        ],
        [
            'id'          => 'admin.workflow_definitions',
            'label'       => 'Workflow Definitions',
            'description' => 'Manage approval workflow definitions',
            'icon'        => 'fas fa-project-diagram',
            'action'      => 'navigate',
            'module'      => 'admin',
            'keywords'    => ['workflows', 'approvals', 'definitions', 'process', 'automation'],
            'category'    => 'Workflows',
            'route'       => 'admin.workflow-definitions',
            'permission'  => 'view_workflow_definitions',
            'roles'       => ['super_admin', 'company_admin'],
        ],
        [
            'id'          => 'admin.access_control',
            'label'       => 'Access Control',
            'description' => 'Manage module-level access control and permissions',
            'icon'        => 'fas fa-shield-alt',
            'action'      => 'navigate',
            'module'      => 'admin',
            'keywords'    => ['access', 'control', 'permissions', 'security', 'authorization'],
            'category'    => 'Access Control',
            'route'       => 'admin.access-control-management',
            'permission'  => 'view_access_control',
            'roles'       => ['super_admin'],
        ],
    ],
];